# Behavior
pixel_scroll yes
momentum_scroll 0
mouse_hide_wait 1.5

# Visual
url_style straight
underline_hyperlinks always
background_opacity 0.9

# General
shell nu
editor nvim

# Startup
startup_session ~/.config/kitty/session.conf

# Keybinds
map kitty_mod+t launch --type=tab --cwd=current

# Fonts
symbol_map       U+1F300-U+1FAFF Apple Color Emoji
font_family      family='SpaceMono Nerd Font' postscript_name=SpaceMonoNF-Regular
bold_font        auto
italic_font      auto
bold_italic_font auto

# Theme
# {# replace_between(`/`, `.conf`, key_by_value(theme, data.theme)) #}
include themes/mocha.conf
