theme = "sonokai"

[editor]
bufferline = "multiple"
cursorline = true
scroll-lines = 1
line-number = "relative"
shell = ["nu", "-c"]
idle-timeout = 200
preview-completion-insert = true
completion-trigger-len = 1
color-modes = true
rulers = [80]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
auto-signature-help = false
display-messages = true

[editor.whitespace.render]
tab = "all"
newline = "none"

[editor.whitespace.characters]
nbsp = "⍽"
tab = "→"
newline = "⏎"

[editor.indent-guides]
character = "╎"
render = true

[editor.statusline]
mode.normal = "\uf06e"
mode.insert = "\uea73"
mode.select = "\uf4f3"
left = ["mode", "spinner", "version-control", "file-name"]

[keys.normal]
X = ["extend_line_up", "extend_to_line_bounds"]

[keys.select]
X = ["extend_line_up", "extend_to_line_bounds"]

