[[language]]
name = "rust"

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[[language]]
name = "python"
language-servers = ["pylsp"]
auto-format = true

[[language]]
name = "pest"
file-types = ["pest"]
indent = { tab-width = 1, unit = " " }
language-servers = ["pest"]
scope = "source.pest"
roots = ["Cargo.toml", "Cargo.lock"]
auto-format = true

[language-server.pest]
command = "pest-language-server"

[language-server.pylsp.config.pylsp]
configurationSources = ["flake8"]

[language-server.pylsp.config.pylsp.plugins]
black = { enabled = true, line_length = 80 }
flake8 = { enabled = true }
autopep8 = { enabled = false }
mccabe = { enabled = false }
pycodestyle = { enabled = false }
pyflakes = { enabled = false }
pylint = { enabled = false }
pyls_isort = { enabled = true }
yapf = { enabled = false }
ruff = { enabled = false }
mypy = { enabled = true, live_mode = true, strict = true }
