cursor            #ffb3b2
cursor_text_color #561d1f

foreground            #f0dedd
background            #140c0c
selection_foreground  #442929
selection_background  #e6bdbb
url_color             #e6bdbb

#: black 000000 767676
color0  #1a1111
color8  #3d3232
#: red cc0403 f2201f
color1  #ff1302
color9  #ffa29b
#: green 19cb00 23fd00
color2  #e6bdbb
color10 #ffdad8
#: yellow cecb00 fffd00
color3  #e4c18d
color11 #ffdead
#: blue 0d73cc 1a8fff
color4  #733334
color12 #ffb3b2
#: magenta cb1ed1 fd28ff
color5  #5d3f3f
color13 #e6bdbb
#: cyan 0dcdcd 14ffff
color6  #5a4319
color14 #e4c18d
#: white dddddd ffffff
color7  #d7c1c0
color15 #f0dedd

mark1_foreground #3b080c
mark1_background #ffdad8
mark2_foreground #2c1515
mark2_background #ffdad8
mark3_foreground #281900
mark3_background #ffdead

active_tab_foreground #561d1f
active_tab_background #ffb3b2
inactive_tab_foreground #ffdad8
inactive_tab_background #733334

active_border_color #ffb3b2
inactive_border_color #561d1f
# bell_border_color #ff5a00