input {
    # Keyboard: Add a layout and uncomment kb_options for Win+Space switching shortcut
    kb_layout = de
    kb_variant = nodeadkeys
    # kb_options = grp:win_space_toggle
    numlock_by_default = false
    repeat_delay = 250
    repeat_rate = 35

    touchpad {
        natural_scroll = yes
        disable_while_typing = false
        clickfinger_behavior = false
        scroll_factor = 0.5
    }
    special_fallthrough = true
    follow_mouse = 1
}
