# Launch terminal
bind = Super, Return, exec, kitty

# Emoji >> clipboard
bindd = Super, period, Emoji >> clipboard, global, quickshell:overviewEmojiToggle

# Mute the mic
bindl = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_SOURCE@ toggle
