#!/usr/bin/env python3
# vim: syntax=python3

import sys
from datetime import date

field_name = sys.argv[1]
match field_name:
    case "Year":
        print(date.today().year)
    case "Author" | "Full name":
        print("Jonas da Silva")

