export const black = "#1E1D2D"
export const green = "#ABE9B3"
export const white = "#D9E0EE"
export const grey = "#282737"
export const blue = "#96CDFB"
export const red = "#F28FAD"
export const darkblue = "#83bae8"
